(define (even? n )
	(= (remainder n 2) 0)
)
(define (square n )
	(* n n)
)

(define (fast-expt a n) 
	(cond ((= n 0) 1)
		((even? n) (square (fast-expt a (/ n 2))))
		(else (* a (fast-expt a (- n 1)))))
)
