(define (squares-of-the-2-lager a b c) 
    (define (smallest x y z) 
        (if (< x y) 
            (if z (smallest x z #f) x)
            (if z (smallest z y #f) y)
        )
    )
    (- (+ (* a a) (* b b) (* c c)) (* (smallest a b c) (smallest a b c)))
)
